cran_packages <- c(
  "AER",
  "broom",
  "broom.mixed",
  "Cairo",
  "cardx",
  "caret",
  "circlize",
  "cluster",
  "cowplot",
  "data.table",
  "dplyr",
  "DT",
  "emmeans",
  "factoextra",
  "flextable",
  "forcats",
  "foreign",
  "fs",
  "ggplot2",
  "ggpubr",
  "ggrepel",
  "ggsignif",
  "ggtext",
  "ggVennDiagram",
  "glmmTMB",
  "glmpca",
  "glmnet",
  "glue",
  "gridExtra",
  "gt",
  "gtsummary",
  "harmony",
  "haven",
  "htmltools",
  "janitor",
  "jsonlite",
  "kableExtra",
  "knitr",
  "lme4",
  "lmerTest",
  "logistf",
  "matrixStats",
  "missForest",
  "NbClust",
  "nullabor",
  "officer",
  "openxlsx",
  "pals",
  "pander",
  "parameters",
  "patchwork",
  "permute",
  "pheatmap",
  "plotly",
  "pls",
  "purrr",
  "quarto",
  "RANN",
  "RColorBrewer",
  "readr",
  "readxl",
  "remotes",
  "reshape2",
  "Rfast",
  "rlang",
  "rmarkdown",
  "RSQLite",
  "scales",
  "sf",
  "shadowtext",
  "sjPlot",
  "spatstat",
  "spdep",
  "stringdist",
  "stringr",
  "tibble",
  "tidyr",
  "tidytext",
  "tidyverse",
  "TMB",
  "UpSetR",
  "vegan",
  "vioplot",
  "yaml"
)

bioc_packages <- c(
  # Core Containers & Utilities
  "Biostrings",
  "ComplexHeatmap",
  "MultiAssayExperiment",
  "multtest",
  "S4Vectors",
  "SummarizedExperiment",
  "TreeSummarizedExperiment",

  # Microbiome & Differential Abundance
  "ALDEx2",
  "ANCOMBC",
  "ape",
  "dada2",
  "DirichletMultinomial",
  "limma",
  "LimROTS",
  "maaslin3",
  "mia",
  "miaTime",
  "miaViz",
  "microbiome",
  "phyloseq",

  # RNA-Seq & Transcriptomics
  "apeglm",
  "DESeq2",
  "edgeR",
  "IHW",
  "sva",
  "tximeta",
  "tximport",

  # Tidyomics
  "plyranges",
  "tidybulk",
  "tidySingleCellExperiment",
  "tidySpatialExperiment",
  "tidySummarizedExperiment",

  # Single-Cell Transcriptomics (OSCA)
  "batchelor",
  "bluster",
  "DropletUtils",
  "scater",
  "scran",
  "scuttle",
  "sechm",
  "SingleR",

  # Spatial Transcriptomics (OSTA)
  "AUCell",
  "Banksy",
  "BayesSpace",
  "EBImage",
  "ggspavis",
  "hoodscanR",
  "imcdatasets",
  "imcRtools",
  "nnSVG",
  "SFEData",
  "SpatialExperiment",
  "SpatialExperimentIO",
  "SpatialFeatureExperiment",
  "spatialLIBD",
  "spicyR",
  "SpotSweeper",
  "STexampleData",
  "VisiumIO",

  # Mass Spectrometry & Metabolomics (Metabonaut & RforMassSpectrometry)
  "CompoundDb",
  "MetaboAnnotation",
  "MetaboCoreUtils",
  "MsBackendMassbank",
  "MsBackendMetaboLights",
  "MsBackendMgf",
  "MsCoreUtils",
  "MsExperiment",
  "QFeatures",
  "Spectra",
  "xcms"
)

# Installed from GitHub after CRAN/Bioc passes
github_packages <- c(
  "biobakery/Maaslin2",
  "stefpeschel/NetCoMi",
  "zdk123/SpiecEasi",
  "GraceYoon/SPRING",
  "RforMassSpectrometry/MsIO",
  "RforMassSpectrometry/RuSirius"
)
