"""Pydantic schemas for API request/response validation."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


# --- Project schemas ---

class ProjectCreate(BaseModel):
    name: str | None = None
    question: str | None = None
    notes: str | None = None
    custom_plan_text: str | None = None
    auto_build: bool = False


class ProjectUpdate(BaseModel):
    name: str | None = None
    question: str | None = None
    notes: str | None = None
    custom_plan_text: str | None = None
    auto_build: bool | None = None
    status: str | None = None
    analysis_plan: dict | None = None


class ProjectOut(BaseModel):
    id: uuid.UUID
    owner_id: str = "default_user"
    tenant_id: str = "default_tenant"
    name: str
    name_source: Literal["default", "auto", "user"] = "default"
    question: str | None
    notes: str | None
    custom_plan_text: str | None = None
    auto_build: bool = True
    status: str
    agent_state: str | None = None
    agent_memory: dict | None = None
    agent_actions: list[dict] | None = None
    study_manifest: dict | None = None
    analysis_plan: dict | None
    project_dir: str | None
    created_at: datetime
    updated_at: datetime
    files: list[UploadedFileOut] = []

    model_config = {"from_attributes": True}


# --- File schemas ---

class UploadedFileOut(BaseModel):
    id: uuid.UUID
    file_role: str | None
    original_name: str | None
    detected_format: str | None
    file_summary: dict | None
    created_at: datetime

    model_config = {"from_attributes": True}


# --- Job schemas ---

class JobOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID
    job_type: str | None
    status: str
    progress: list[dict] | None
    logs: str | None
    error: str | None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# --- Analysis plan schemas ---

class WorkflowStep(BaseModel):
    id: str
    name: str
    classification: str  # "standard" or "contested"
    recipe_id: str | None = None
    enabled: bool = True
    rationale: str | None = None
    ensemble_methods: list[dict] | None = None
    parameters: dict | None = None


class AnalysisPlan(BaseModel):
    """The structured analysis plan generated by the LLM planner."""
    project_name: str
    domain: str = "microbiome"
    report_pack_id: str | None = None
    capabilities: list[str] = Field(default_factory=list)
    study_type: str
    question: str
    detected_inputs: list[dict] = Field(default_factory=list)
    grouping_variable: str | None = None
    group_levels: list[str] = Field(default_factory=list)
    covariates: list[str] = Field(default_factory=list)
    workflow: list[WorkflowStep] = Field(default_factory=list)
    estimated_runtime_minutes: float | None = None
    recipe_registry_version: str | None = None
    notes: str | None = None


class PlanRequest(BaseModel):
    """Request body for the planning endpoint."""
    project_id: uuid.UUID


class PlanApproval(BaseModel):
    """User approves (possibly modified) plan."""
    project_id: uuid.UUID
    plan: AnalysisPlan


class ClarificationQuestion(BaseModel):
    """A single multi-option question the planner asks before it can plan."""
    id: str
    prompt: str
    options: list[str] = Field(default_factory=list)
    multiple: bool = False
    allow_custom: bool = False
    depends_on: str | None = None


class ClarificationRequest(BaseModel):
    """Planner output when the study design cannot be inferred."""
    message: str
    questions: list[ClarificationQuestion] = Field(default_factory=list)


class ClarificationAnswer(BaseModel):
    """User's answer to one ClarificationQuestion."""
    id: str
    values: list[str] = Field(default_factory=list)


class ClarificationsSubmit(BaseModel):
    """Answers posted back to the planning flow."""
    answers: list[ClarificationAnswer] = Field(default_factory=list)


class GenerateRequest(BaseModel):
    """Request to generate the Quarto project from an approved plan."""
    project_id: uuid.UUID


class RunRequest(BaseModel):
    """Request to execute quarto render on a generated project."""
    project_id: uuid.UUID


class EditRequest(BaseModel):
    """Request to edit project source code via natural language prompt."""
    instruction: str


class AssistantRequest(BaseModel):
    """Conversational prompt for the workspace assistant."""
    message: str
    history: list[dict[str, str]] = Field(default_factory=list)


class AssistantResponse(BaseModel):
    """Assistant reply — guidance, status, or an edit suggestion."""
    type: str
    message: str
    instruction: str | None = None

class MessageAttachment(BaseModel):
    """Metadata needed to render a file attached to a conversational turn."""
    id: str | None = None
    name: str = Field(min_length=1, max_length=512)
    format: str | None = Field(default=None, max_length=64)
    mime_type: str | None = Field(default=None, max_length=255)
    size_bytes: int | None = Field(default=None, ge=0)
    r_path: str | None = Field(default=None, max_length=1024)
    source: str | None = Field(default=None, max_length=32)


class WorkspaceAgentRequest(BaseModel):
    """A message plus the user's live workspace focus."""
    message: str
    selected_file: str | None = None
    selected_content: str | None = None
    selected_content_dirty: bool = False
    preview_path: str | None = None
    chat_mode: str = "build"  # build | discuss
    idempotency_key: str | None = Field(default=None, max_length=255, description="Stable client key for safe turn retries")
    attachments: list[MessageAttachment] = Field(default_factory=list, max_length=20)


class FileLocksUpdate(BaseModel):
    """Replace the project's locked source paths."""
    paths: list[str] = Field(default_factory=list)


NoteCellType = Literal["markdown", "agent", "code", "output", "provenance"]
NoteThreadStatus = Literal["active", "archived"]


class NoteThreadCreate(BaseModel):
    title: str = Field(default="Untitled note", min_length=1, max_length=255)
    thread_type: str = Field(default="note", min_length=1, max_length=32)


class NoteThreadAttach(BaseModel):
    project_id: uuid.UUID


class NoteThreadWorkspaceCreate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=255)
    question: str | None = Field(default=None, max_length=20_000)
    notes: str | None = Field(default=None, max_length=20_000)
    auto_build: bool = True


class NoteThreadUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=255)
    status: NoteThreadStatus | None = None
    metadata: dict[str, Any] | None = None


class DatasetImportRequest(BaseModel):
    package: str = Field(min_length=1, max_length=128)
    dataset: str = Field(min_length=1, max_length=128)


class NoteThreadTurnRequest(BaseModel):
    message: str = Field(min_length=1, max_length=20_000)
    auto_execute: bool = True
    idempotency_key: str | None = Field(default=None, max_length=255, description="Stable client key for safe turn retries")


class NoteThreadReportExportRequest(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=255)
    slug: str | None = Field(default=None, min_length=1, max_length=80, pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*")
    overwrite: bool = False


class NoteCellCreate(BaseModel):
    cell_type: NoteCellType
    language: str | None = Field(default=None, max_length=32)
    content: str = Field(default="", max_length=2_000_000)
    position: int | None = Field(default=None, ge=0)
    metadata: dict[str, Any] | None = None


class NoteCellRevisionCreate(BaseModel):
    cell_type: NoteCellType
    language: str | None = Field(default=None, max_length=32)
    content: str = Field(default="", max_length=2_000_000)
    metadata: dict[str, Any] | None = None


class NoteCellExecutionCreate(BaseModel):
    revision: int | None = Field(default=None, ge=1)
    parameters: dict[str, Any] = Field(default_factory=dict)
    timeout_seconds: int | None = Field(default=None, ge=1, le=1800)
    cache_policy: Literal["off", "reuse"] = "off"
    upstream_execution_ids: list[uuid.UUID] = Field(default_factory=list, max_length=64)


class NoteExecutionArtifactOut(BaseModel):
    id: uuid.UUID
    execution_id: uuid.UUID
    artifact_type: str
    relative_path: str
    mime_type: str
    byte_size: int
    sha256: str
    metadata: dict[str, Any] | None = None
    created_at: datetime


class NoteCellExecutionOut(BaseModel):
    id: uuid.UUID
    revision_id: uuid.UUID
    attempt: int
    status: str
    execution_kind: str
    timeout_seconds: int
    cancel_requested: bool
    environment_fingerprint: str | None
    input_fingerprint: str | None
    parameters: dict[str, Any] | None = None
    result_metadata: dict[str, Any] | None = None
    artifacts: list[NoteExecutionArtifactOut] = Field(default_factory=list)
    error: str | None
    started_at: datetime | None
    finished_at: datetime | None
    created_at: datetime
    event_sequence: int
    cache_policy: str
    cache_key: str | None
    dependency_fingerprint: str | None
    upstream_execution_ids: list[uuid.UUID] = Field(default_factory=list)
    cache_hit: bool
    cache_source_execution_id: uuid.UUID | None


class NoteExecutionEventOut(BaseModel):
    id: uuid.UUID
    execution_id: uuid.UUID
    sequence: int
    event_type: str
    status: str
    payload: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime


class NoteCellRevisionOut(BaseModel):
    id: uuid.UUID
    cell_id: uuid.UUID
    revision: int
    cell_type: NoteCellType
    language: str | None
    content: str
    metadata: dict[str, Any] | None = None
    created_by: str | None
    created_at: datetime


class NoteCellOut(BaseModel):
    id: uuid.UUID
    thread_id: uuid.UUID
    position: int
    status: str
    revisions: list[NoteCellRevisionOut] = Field(default_factory=list)
    latest_execution: NoteCellExecutionOut | None = None
    created_at: datetime
    updated_at: datetime


class NoteThreadSummaryOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID | None
    scope: Literal["standalone", "workspace"]
    title: str
    thread_type: str
    status: NoteThreadStatus
    metadata: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class NoteThreadOut(NoteThreadSummaryOut):
    cells: list[NoteCellOut] = Field(default_factory=list)


class ReportOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID
    name: str
    slug: str | None = Field(default=None, min_length=1, max_length=80, pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*")
    report_type: str
    status: str
    source_path: str | None
    rendered_path: str | None
    metadata: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class ProjectMessageOut(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID
    role: str
    kind: str
    content: str
    message_metadata: dict[str, Any] | None = Field(
        default=None,
        validation_alias="message_metadata",
        serialization_alias="metadata",
    )
    cell_id: uuid.UUID | None = None
    cell_type: str | None = None
    cell_revision: int | None = None
    execution_id: uuid.UUID | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


# Forward reference resolution
ProjectOut.model_rebuild()
