

```{r setup_m}

source("../funct.R")
# Load the TreeSummarizedExperiment object
tse <- readRDS("../../data/tse.Rds")

pa_tse <- altExp(tse, "pathabundance")

prevalence.th <- 10/100
detection.th <- 0.1/100

variable <- "Intervention" 
formula_used <- "~ Intervention * time + (1 | id)"
correction <- "Benjamini-Hochberg FDR adjustment"

```

## Maaslin3 significant hits

This section highlights significant taxa from maaslin3.

Analysis information:

-   Method: maaslin3
-   Group variable: `r variable`
-   Formula used: **`r formula_used`**
-   Correction: **`r correction`**
-   Detection threshold: `r 100 * detection.th`%
-   Prevalence threshold: `r 100 * prevalence.th`%

```{r tsesub_m}
file_path1 <- file.path("../../output/daa/daa_pa/interaction/significant_results.tsv")
file_path2 <- file.path("../../output/daa/daa_pa/4/significant_results.tsv")
file_path3 <- file.path("../../output/daa/daa_pa/B/significant_results.tsv")
file_path4 <- file.path("../../output/daa/daa_pa/C/significant_results.tsv")
daa_tab1 <- read_tsv(file_path1, col_names = TRUE, show_col_types = FALSE)
daa_tab2 <- read_tsv(file_path2, col_names = TRUE, show_col_types = FALSE) 
daa_tab3 <- read_tsv(file_path3, col_names = TRUE, show_col_types = FALSE)
daa_tab4 <- read_tsv(file_path4, col_names = TRUE, show_col_types = FALSE)
daa_tab1 <- na.omit(daa_tab1)
daa_tab2 <- na.omit(daa_tab2)
daa_tab3 <- na.omit(daa_tab3)
daa_tab4 <- na.omit(daa_tab4)
significant_fxns <- unique(c(daa_tab1$feature, daa_tab2$feature, daa_tab3$feature, daa_tab4$feature))

target_list <- rownames(pa_tse)

closest_matches <- sapply(significant_fxns, function(x) {
  target_list[which.min(stringdist(x, target_list, method = "jw"))]
})

```

```{r before-after_m}
df <- mia::meltSE(pa_tse, add.col = T, assay.type = "relabundance")

df_not_zer0 <- df %>%
    group_by(FeatureID, time, Treatment) %>%
    summarise(
        nonzero_n = sum(relabundance > 0, na.rm = TRUE),
        total_n = sum(!is.na(relabundance)),
        pct_nonzero = round(100 * nonzero_n / total_n, 1),
        .groups = "drop"
    ) %>%
    filter(nonzero_n > 0) %>%
    pivot_wider(
        names_from = c(time, Treatment),
        values_from = c(nonzero_n, total_n, pct_nonzero),
        names_glue = "{Treatment}_{time}_{.value}"
    )

```

```{r}
plots_list <- list()
plots_list <- setNames(lapply(closest_matches, function(taxon_name) {
    
    p1 <- plotBoxplot( pa_tse, assay.type = "relabundance", x = "Intervention",  fill.by = "time", pair.by = "subject", features = c(taxon_name), facet.by = "rownames", add.change = T, add.significance = T, ncol = 1, label.size = 5) +
      theme_minimal(base_size = 15) +
  theme(text = element_text(family = "Roboto", size = 15),
        strip.text = element_blank(),
        axis.text = element_text(face = "bold"),
  ) + labs(title = taxon_name)

    p2 <- plotBoxplot( pa_tse, assay.type = "relabundance", x = "time",  fill.by = "Intervention", features = c(taxon_name), facet.by = "rownames", add.significance = T, ncol = 1, label.size = 5) +
        scale_fill_viridis_d(option = "D") +
      theme_minimal(base_size = 15) +
  theme(text = element_text(family = "Roboto", size = 15), 
        strip.text = element_blank(),
        axis.text = element_text(face = "bold"),
  )
    
    label_text <- generate_prevalence_label(df_not_zer0, taxon_name)
    
    p12 <- wrap_plots(p1, p2, axes = "collect") + 
      labs(caption = label_text) +
      theme(
    plot.caption = element_text(size = 13, 
                                face = "bold.italic", 
                                hjust = 1, color = "darkblue") )
    
    return(p12)
    
}
    ),
 closest_matches)

```

```{r hits_m}
#| layout-ncol: 1
#| fig-width: 16 
#| fig-height: 6 

ordered_plots <- plots_list[order(names(plots_list))]

for (plot_name in names(ordered_plots)) {
  print(ordered_plots[[plot_name]])
}

```

## Session info

::: {.callout-note collapse="true" title="Show session information"}
```{r session-info}
#| label: session-info
sessionInfo()
```
:::
